server:
  port: 8080

spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive

  cloud:
    gateway:
      server:
        webflux:
          default-filters:
            - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
            - id: auth-service
              uri: lb://auth-service
              predicates:
                - Path=/auth/**
              filters:
                - StripPrefix=1
                - name: CircuitBreaker
                  args:
                    name: authCircuitBreaker
                    fallbackUri: forward:/fallback/auth-service

            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/users/**
              filters:
                - StripPrefix=1
                - name: CircuitBreaker
                  args:
                    name: userCircuitBreaker
                    fallbackUri: forward:/fallback/users-service

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0
    enabled: true
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_SERVER:http://localhost:9411/api/v2/spans}
  metrics:
    tags:
      application: ${spring.application.name}
  prometheus:
    metrics:
      export:
        enabled: true

security:
  jwt:
    issuer: api-gateway
    secret: "change-this-in-prod-64chars-minimum______________________________"
    expiration-seconds: 3600 # (1 hour)
