server:
  port: 8080

spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      server:
        webflux:
          default-filters:
            - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
            - id: auth-service
              uri: lb://auth-service
              predicates:
                - Path=/auth/**
              filters:
                - StripPrefix=1
                - name: CircuitBreaker
                  args:
                    name: authCircuitBreaker
                    fallbackUri: forward:/fallback/auth-service
                - name: Retry
                  args:
                    retries: 3
                    statuses: BAD_GATEWAY, GATEWAY_TIMEOUT, SERVICE_UNAVAILABLE
                    methods: GET, POST, PUT

            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/users/**
              filters:
                - StripPrefix=1
                - name: CircuitBreaker
                  args:
                    name: userCircuitBreaker
                    fallbackUri: forward:/fallback/users-service
                - name: Retry
                  args:
                    retries: 3
                    statuses: BAD_GATEWAY, GATEWAY_TIMEOUT, SERVICE_UNAVAILABLE
                    methods: GET, POST, PUT

            - id: media-service
              uri: lb://media-service
              predicates:
                - Path=/media/**
              filters:
                - StripPrefix=1
                - name: CircuitBreaker
                  args:
                    name: mediaCircuitBreaker
                    fallbackUri: forward:/fallback/media-service
                - name: Retry
                  args:
                    retries: 3
                    statuses: BAD_GATEWAY, GATEWAY_TIMEOUT, SERVICE_UNAVAILABLE
                    methods: GET, POST, PUT

            - id: campaign-service
              uri: lb://campaign-service
              predicates:
                - Path=/campaigns/**
              filters:
                - StripPrefix=1
                - name: CircuitBreaker
                  args:
                    name: campaignCircuitBreaker
                    fallbackUri: forward:/fallback/campaign-service
                - name: Retry
                  args:
                    retries: 3
                    statuses: BAD_GATEWAY, GATEWAY_TIMEOUT, SERVICE_UNAVAILABLE
                    methods: GET, POST, PUT

            - id: notification-service
              uri: lb://notification-service
              predicates:
                - Path=/notifications/**
              filters:
                - StripPrefix=1
                - name: CircuitBreaker
                  args:
                    name: notificationCircuitBreaker
                    fallbackUri: forward:/fallback/notification-service
                - name: Retry
                  args:
                    retries: 3
                    statuses: BAD_GATEWAY, GATEWAY_TIMEOUT, SERVICE_UNAVAILABLE
                    methods: GET, POST, PUT

            - id: donation-service
              uri: lb://donation-service
              predicates:
                - Path=/donations/**
              filters:
                - StripPrefix=1
                - name: CircuitBreaker
                  args:
                    name: donationCircuitBreaker
                    fallbackUri: forward:/fallback/donation-service
                - name: Retry
                  args:
                    retries: 3
                    statuses: BAD_GATEWAY, GATEWAY_TIMEOUT, SERVICE_UNAVAILABLE
                    methods: GET, POST, PUT

            - id: payout-service
              uri: lb://payout-service
              predicates:
                - Path=/payouts/**
              filters:
                - StripPrefix=1
                - name: CircuitBreaker
                  args:
                    name: donationCircuitBreaker
                    fallbackUri: forward:/fallback/payout-service
                - name: Retry
                  args:
                    retries: 3
                    statuses: BAD_GATEWAY, GATEWAY_TIMEOUT, SERVICE_UNAVAILABLE
                    methods: GET, POST, PUT
          httpclient:
            max-header-size: 16384 # 16 KB
            max-initial-line-length: 16384 # 16 KB
            response-timeout: 30s
  webflux:
    multipart:
      max-in-memory-size: 10MB
  http:
    codecs:
      max-in-memory-size: ${MAX_FILE_SIZE:50MB}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:9061/eureka/}
    registry-fetch-interval-seconds: 5
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0
    enabled: true
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_SERVER:http://localhost:9411/api/v2/spans}
  metrics:
    tags:
      application: ${spring.application.name}
  prometheus:
    metrics:
      export:
        enabled: true

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        failureRateThreshold: 70
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        minimumNumberOfCalls: 5
        slowCallDurationThreshold: 3s
        slowCallRateThreshold: 100
    instances:
      authCircuitBreaker:
        baseConfig: default
      userCircuitBreaker:
        baseConfig: default
      mediaCircuitBreaker:
        baseConfig: default
      campaignCircuitBreaker:
        baseConfig: default
      notificationCircuitBreaker:
        baseConfig: default
      donationCircuitBreaker:
        baseConfig: default
      payoutCircuitBreaker:
        baseConfig: default

  timelimiter:
    configs:
      default:
        cancelRunningFuture: true
        timeoutDuration: 10s   # 🔹 aumentamos de 1s a 5s
    instances:
      authCircuitBreaker:
        baseConfig: default
      userCircuitBreaker:
        baseConfig: default
      mediaCircuitBreaker:
        baseConfig: default
      campaignCircuitBreaker:
        baseConfig: default
      notificationCircuitBreaker:
        baseConfig: default
      donationCircuitBreaker:
        baseConfig: default
      payoutCircuitBreaker:
        baseConfig: default


security:
  jwt:
    issuer: api-gateway
    secret: "change-this-in-prod-64chars-minimum______________________________"
    expiration-seconds: 3600 # (1 hour)
