server:
  port: 8080

spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive

  cloud:
    gateway:
      server:
        webflux:
          default-filters:
            - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
            - id: auth-service
              uri: lb://auth-service
              predicates:
                - Path=/auth/**
              filters:
                - StripPrefix=1
                - name: CircuitBreaker
                  args:
                    name: authCircuitBreaker
                    fallbackUri: forward:/fallback/auth-service

            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/users/**
              filters:
                - StripPrefix=1
                - name: CircuitBreaker
                  args:
                    name: userCircuitBreaker
                    fallbackUri: forward:/fallback/users-service

            - id: media-service
              uri: lb://media-service
              predicates:
                - Path=/media/**
              filters:
                - StripPrefix=1
                - name: CircuitBreaker
                  args:
                    name: mediaCircuitBreaker
                    fallbackUri: forward:/fallback/media-service

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0
    enabled: true
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_SERVER:http://localhost:9411/api/v2/spans}
  metrics:
    tags:
      application: ${spring.application.name}
  prometheus:
    metrics:
      export:
        enabled: true

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        minimumNumberOfCalls: 5
        slowCallDurationThreshold: 3s
        slowCallRateThreshold: 100
    instances:
      authCircuitBreaker:
        baseConfig: default
      userCircuitBreaker:
        baseConfig: default
      mediaCircuitBreaker:
        baseConfig: default

  timelimiter:
    configs:
      default:
        cancelRunningFuture: true
        timeoutDuration: 5s   # 🔹 aumentamos de 1s a 5s
    instances:
      authCircuitBreaker:
        baseConfig: default
      userCircuitBreaker:
        baseConfig: default


security:
  jwt:
    issuer: api-gateway
    secret: "change-this-in-prod-64chars-minimum______________________________"
    expiration-seconds: 3600 # (1 hour)
