name: Release

on:
  push:
    branches:
      - 'release/*'

jobs:
  release-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Extract version from branch
        run: echo "VERSION=${GITHUB_REF#refs/heads/release/}" >> $GITHUB_ENV

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Update Maven version
        run: mvn versions:set -DnewVersion=${{ env.VERSION }}

      - name: Run Tests
        run: mvn test -B

      - name: Build Package
        run: mvn clean package -DskipTests

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository }}/app
          docker build -t $IMAGE_NAME:${{ env.VERSION }} .
          docker push $IMAGE_NAME:${{ env.VERSION }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.VERSION }}
