name: Verify

on:
  push:
    branches:
      - develop
      - 'feature/*'
      - 'fix/*'
      - 'hotfix/*'
  pull_request:
    branches:
      - develop

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Run Checkstyle + PMD
        run: mvn checkstyle:check pmd:check -B

      - name: Run Unit Tests
        run: mvn test -B
